# Generated by Django 4.0.5 on 2022-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('adress', models.TextField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
