# Generated by Django 4.0.5 on 2022-06-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, default='', help_text='Informe seu endereço completo.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, default='', help_text='Informe seu cpf completo', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(help_text='Informe o seu nome completo', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(help_text='Informe o nome completo de sua mãe', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Informe seu número de telefone', max_length=11, null=True),
        ),
    ]
