# Generated by Django 4.0.5 on 2022-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleform', '0003_alter_person_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Número de CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(max_length=255, verbose_name='Nome da Mãe Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
