# Generated by Django 4.0.5 on 2022-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleform', '0004_alter_person_adress_alter_person_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, default='', help_text='Insira o endereço seguido de uma referência que auxilie a encontrar sua localidade.', max_length=512, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, default='', help_text='Insira somente número CPF.', max_length=11, null=True, verbose_name='Número de CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(help_text='Insira o nome completo.', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(help_text='Insira o nome da sua mãe completo.', max_length=255, verbose_name='Nome da Mãe Completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Insira número de telefone com o DDD. (Ex.: 91983243576)', max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
