# Generated by Django 4.0.5 on 2022-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleform', '0005_alter_person_adress_alter_person_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, help_text='Insira somente número CPF.', max_length=11, null=True, unique=True, verbose_name='Número de CPF'),
        ),
    ]
